csi-nfs-plugin/mapfs_linux_amd64:
  size: 3494986
  object_id: b48b3ebb-881d-4197-46b9-a74a4923629c
  sha: 39494312e1fc41b81a7ebfc97c6542635f3e950c
csi-nfs-plugin/rootfs.tgz:
  size: 140047952
  object_id: ce8c28ee-cef3-481c-5f80-02b3ec42b0c9
  sha: 90535d4bdc6e2bba68523d53c3ce1a6beb3cca54
golang/go1.10.linux-amd64.tar.gz:
  size: 119905205
  object_id: 79de1033-ed80-47a5-7823-d28d165b46a2
  sha: 693e2dfd99ef2d608b41c450efd9d277bf2a7f2f
